version: '3.2'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: txbank
      POSTGRES_USER: txbank
      POSTGRES_PASSWORD: txbank
      PGDATA: /var/lib/pg_data
    ports:
      - "5656:5432"
    volumes:
      - ./.docker/pgdata:/var/lib/postgresql/data