version: '3.2'
services:
  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB=txbank
      - POSTGRES_USER=txbank
      - POSTGRES_PASSWORD=txbank
      - PGDATA=/var/lib/pg_data
      - TZ=Asia/Jakarta
    ports:
      - "5656:5432"
    volumes:
      - ./.docker/pgdata:/var/lib/postgresql/data